version: "3"

vars:
  BINARY_NAME: nem.exe
  CMD_PATH: ./cmd/cli

tasks:
  default:
    desc: Build the application
    deps: [build]

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.CMD_PATH}}

  run:
    desc: Run the application
    cmds:
      - go run {{.CMD_PATH}}

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - go clean